site_name: Записки шизофреника
site_url: https://rustbas.github.io/blog
repo_url: https://github.com/rustbas/blog
edit_uri: edit/main/docs/
theme:
    name: terminal
    palette: dark
    features:
      - revision.date
      - revision.history

nav:
  - "Обо мне": 'index.md'
  - "Математика": 'maths/index.md'

plugins:
  - search:
      lang: ["ru", "en"]
      indexing: 'full'
  - git-revision-date

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
