site_name: Записки шизофреника
site_url: https://rustbas.github.io/blog
theme:
    name: terminal
    palette: dark

plugins:
  - search:
      lang: ["ru", "en"]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
