site_name: Очередные записки очередного гика
site_url: https://rustbas.github.io/blog
repo_url: https://github.com/rustbas/blog
edit_uri: edit/main/docs/
theme:
    name: material
    palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: green

    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: teal
      
    features:
      - navigation.instant # TODO: check troubles with TeX loading
      - navigation.instant.progress
      - header.autohide
    icon:
      repo: fontawesome/brands/git
    font:
      # text: Roboto
      code: JetBrains Mono

    #   - revision.date
    #   - revision.history
    #   - navigation.side.hide
nav:
  # - "Обо мне": 'index.md'
  - "Математика": 'maths/index.md'
  - "Linux": 'linux/index.md'
  - "Общее": 'common/index.md'

plugins:
  - search:
      lang: ["ru", "en"]
      indexing: 'full'
  - git-revision-date
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
